deployName: appdeploypoc
appName: singlepageapp
environment: stg
version: "1.0"


service:
  type: ClusterIP
  port: "80"

image:
  repository: ajdockerspace/singlepageapp:v1.0

namespace:
  name: appdeploypoc

ingress:    
  hostName: singlepageapp.ajith-s-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com            
  livePathType: Prefix
  livePath: /prod(/|$)(.*)
  secondaryPathType: Prefix
  secondaryPath: /stg(/|$)(.*) 