kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    name: {{ .Values.appName }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}    
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}  
      version: "0.1"
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}  
        version: "0.1"
    spec:
      containers:
        - image: {{ .Values.image.repository }}
          name: {{ .Chart.Name }}
          ports:
            - containerPort: 80