# kind: Namespace
# apiVersion: v1
# metadata:
#   name: {{ .Values.namespace.name }}
#   labels:
#     name: {{ .Values.appName }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}    
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      imagePullSecrets:
      - name: docker
      containers:
        - image: {{ .Values.image.repository }}
          name: {{ .Values.appName }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
