apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.appName }}      
spec:
  # type: NodePort
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}  
    version: "0.1"
  ports:
    - name: singlepageapp-port
      protocol: TCP
      port: 80
      targetPort: 80