apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.appName }}      
spec:
  # type: NodePort
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}
  ports:
    - name: apiapp-port
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
